# Generated by Django 4.0.8 on 2023-01-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('Desc', models.CharField(max_length=30)),
                ('Date', models.DateField(max_length=30)),
            ],
        ),
    ]
